import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";

import "normalize.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "PromicLegis",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css"
				/>
			</head>

			<body className={inter.className}>{children}</body>
		</html>
	);
}
